# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='\u6635\u79f0')),
                ('author_email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('author_url', models.CharField(blank=True, max_length=200, verbose_name='\u7f51\u5740')),
                ('author_ip', models.GenericIPAddressField(blank=True, default='', null=True, verbose_name='\u6765\u6e90IP')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u8bc4\u8bba\u65e5\u671f')),
                ('content', models.TextField(verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('parent', models.BigIntegerField(default=0, verbose_name='\u7236\u7ea7\u8bc4\u8bbaID')),
                ('approved', models.IntegerField(choices=[(0, '\u901a\u8fc7'), (1, '\u672a\u5ba1\u6838'), (2, '\u5783\u573e'), (3, '\u9690\u85cf')], default=1, verbose_name='\u8bc4\u8bba\u72b6\u6001')),
                ('level', models.IntegerField(default=0, verbose_name='\u8bc4\u8bba\u5c42\u7ea7')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='\u6587\u7ae0')),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': '\u8bc4\u8bba\u5217\u8868',
                'verbose_name_plural': '\u8bc4\u8bba\u7ba1\u7406',
            },
        ),
    ]
