# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 09:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u6b63\u6587')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='\u53d1\u5e03\u65e5\u671f')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005')),
            ],
        ),
    ]
